### ISSUE TITLE
ADDON.DAT Purpose

### ISSUE THREAD

**Issue by coldReactive** [carriejv/libxivdat#2]
Minor Update to the Table in case you ever see this again. The ADDON.DAT is for Job Gauge and other relevant settings. Since it saves if a Job Gauge is set to Simple Mode or not.

**Comment by carriejv** [comment]
Yeah, thanks for the info. To be honest Dalamud has kind of leapfrogged this little project so I haven't updated it in quite awhile, but I'll be sure to update it next time I do some maintenance.
